# Generated by Django 3.1.1 on 2020-09-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200924_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='artist',
            new_name='user',
        ),
    ]
